BUG: VTK slice reader
volodia99/nonos pull request #353
Opened 2024-09-23 12:14 UTC by volodia99

2024-09-23 12:27 UTC, neutrinoceros requested changes
Did we check that other curvilinear geometries are fine ?

2024-09-23 12:27 UTC, neutrinoceros commented on tests/test_load_data.py
> +    )
Suggestion to improve readability
```suggestion
    rho_slice_pp = ds["RHO"].azimuthal_at_phi(np.pi)
    rho_slice_cut = ds_phi_cut["RHO"]
    np.testing.assert_array_almost_equal(rho_slice_pp.data, rho_slice.data)
    
    for coord in ("r", "theta"):
    		np.testing.assert_array_almost_equal(
    		    getattr(rho_slice_pp.coords, coord),
    		    getattr(rho_slice_cut.coords, coord),
    		)
    )
```
(The rest of the test should be refactored as a `@pytest.mark.parametrize`d test) 

It would also be great to add an explicit tolerance.

2024-09-23 14:27 UTC, volodia99 commented
> Did we check that other curvilinear geometries are fine ?

If you mean polar 3D, no!

2024-09-25 09:58 UTC, volodia99 commented on tests/test_load_data.py
> +    )
OK I can rewrite all the test this way, but not sure to know how to use  `@pytest.mark.parametrize` when the parameter to change is a method ? :thinking:

2024-09-25 13:24 UTC, merged